### ISSUE TITLE
make sure that incoming data packets don't get overwritten on the same day

### ISSUE THREAD

**Issue by juandlt-csu** [rossyndicate/poudre_sonde_network#102]
from #101 from @kathryn-willi 
suggestion: A way to make sure files don't get overwritten on the same day... If we replace the current write_csv() call in api_puller with the following code that includes the full end_dt:

`write_csv(one_df,
              paste0(dump_dir, "/", site, "_",
                     str_replace(str_replace(substr(end_dt, 1, 16), "[:\\s]", "_"), ":", ""),
                     ".csv"))`

**Comment by juandlt-csu** [comment]
this has been incorporated in my fork, I just need to open a PR for it

**Comment by kathryn-willi** [comment]
ahh, yes. Good catch and looking forward to the fix!
