### ISSUE TITLE
Render new iteration of 01_organize_raw_data.Rmd

### ISSUE THREAD

**Issue by kathryn-willi** [rossyndicate/poudre_sonde_network#20]
It would be helpful to submit the rendered .html so figures can be reviewed more easily.

**Comment by juandlt-csu** [comment]
Would this be submitting the html file itself or the figures that are produced with ggplot? Can the html be rendered in GitHub? When I tried to do this I could only see the code that made up the html file, but I couldn't see the rendered file.

**Comment by kathryn-willi** [comment]
Rendered .html's can't be visualized on GitHub, but all you have to do is download them. It's just nice when a PR is more related to a philosophical question/not the code, and we only need to review figures or text. So! To answer your question, be sure to submit the .html file itself!

**Comment by juandlt-csu** [comment]
Ohh okay, that makes sense.
