### ISSUE TITLE
Histograms of all parameter/site combos

### ISSUE THREAD

**Issue by kathryn-willi** [rossyndicate/poudre_sonde_network#41]

**Comment by juandlt-csu** [comment]
I forget what the goal for this issue was... What do we want to use these histograms for?

**Comment by kathryn-willi** [comment]
To see what the range of values for a given parameter are. For example, we can use a histogram to see how frequently turbidity was above 100 NTU at a given site. Can be used to determine what our thresholds should be in a visual way!

**Comment by juandlt-csu** [comment]
### Tasks:

- add (n = number of measurements) to the title of the histograms.
- add data subfolder for the images that are produced.
- change the months for the seasonal histograms so that they align with hydrology related seasons.
    - snowmelt = 4,5,6
    - monsoon = 7,8
    - fall baseflow = 9,10,11
    - winter baseflow = 12,1,2,3

**Comment by juandlt-csu** [comment]
The histograms have been made and are ripe for exploration!
