### ISSUE TITLE
Appending 6-hour data from API

### ISSUE THREAD

**Issue by kathryn-willi** [rossyndicate/poudre_sonde_network#73]
Work will be centered within the `api_pull` folder

**Comment by kathryn-willi** [comment]
UPDATE: can we actually do this in 3-hour increments instead?

**Comment by juandlt-csu** [comment]
We can do this in 3-hour increments but we will need to append to the previous 6 hours of data for the large anomaly flag to work on the more recent incoming data point.

**Comment by juandlt-csu** [comment]
This is mostly done, just need to append to historical API data and we should be good. historical flagged data and appending to incoming data is done.

**Comment by juandlt-csu** [comment]
need to revisit this to make sure that the workflow is working how we expect it to when it comes to flagged data since it is being flagged twice.

**Comment by juandlt-csu** [comment]
I am going to mark this as done. Everything seems to be working properly. We have not tested this extensively.
