### ISSUE TITLE
API pull broken

### ISSUE THREAD

**Issue by SamStruthers** [rossyndicate/poudre_sonde_network#86]
Attempted to run the QAQC script and got the following error:
Error in `filter()`:
ℹ In argument: `!grepl("vulink", name, ignore.case = TRUE)`.
Caused by error:
! object 'name' not found

I would investigate but don't want to alter downstream uses that y'all might be working on

**Comment by juandlt-csu** [comment]
This was an error in the QAQC targets pipeline or the Rmd script?

**Comment by SamStruthers** [comment]
RMD (line: all_data <- munge_api_data(api_path = "data/api/historical_api_data/")
 Have not yet looked into the targets pipeline

**Comment by juandlt-csu** [comment]
I think I fixed the error in munge_api_data(). You can go ahead and git pull and try again. If that works you can go ahead and close this issue.

**Comment by SamStruthers** [comment]
Fixed! Thanks
