### ISSUE TITLE
Flagging data for believable range for CLP

### ISSUE THREAD

**Issue by SamStruthers** [rossyndicate/poudre_sonde_network#97]
I have been making some summary tables for PWQN sites and have noticed that new sites (Tamasag and River Bluffs) have a bunch of erroneous data getting past QAQC. A lot of these data seem to be related to when a sonde was buried in sediment or out of the water. 
Below is an example of pH data in April from Tamasag (points) and Legacy (black line). Some of the data is successfully being flagged (blue) but a considerable amount is getting past (red)
![Tamasag_pH_04_23_flags](https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/19142144-eeb6-40e2-b0da-5d6717c92077)

My guess is that because these sites are newer, the seasonal flag is rendered ineffective and since is does not violate the slope or sd flags, these data are allowed to pass. 
Possible solution: We could create Poudre wide sensor spec ranges based on our four years of data and create some simple bounds for some parameters. ie pH in the Poudre is generally between 6 and 10 across all sites
Alternatively, these data just need to be flagged manually and these issues should be resolved for future years when the seasonal flag has better bounds.

**Comment by kathryn-willi** [comment]
I like the idea of creating a flag from parameter bounds based on our understanding of the system as you suggest here!

**Comment by SamStruthers** [comment]
Did some investigating into this and found three parameters that I think this could be valid for: pH, SC and temp. 
Overall, I have learned that most of these data occur when the sonde is out of the water but is either missed by site visit flag, was recording during storage or was not properly deployed in the stream. 

pH is definitely the most obvious and I'm proposing the bounds 6 to 10. The plots below show all the pre 2023 data (raw) and 2023 data (current QAQC applied). We could be more aggressive on the bounds (see timeline) but hopefully this flag will cause the slope flag to actually flag more data. 
![pH_real_range](https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/67e55be7-84a4-4c81-8eb8-47a5bcdf784b)
![pH_real_timeline](https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/d111461f-a77a-4b39-8715-6261c9112d26)
For SC, I'm proposing the bounds 30 to 2500. Few sites in the PWQN get above 2200 unless they are logging when being stored with pH 4. However, boxcreek (ag trib) gets above 2200 so I think 2500 is conservative enough to remove the really erroneous data while not removing possible data. On the lower end, our most upstream sites usually hover around 40 SC. I also checked the City's sonde data up the canyon (final plot in the SC section) and it never got below 30 unless there was an outlier. 
![SC_real_range](https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/1fd25def-627f-4105-8079-26047ae9c147)
![SC_real_timeline](https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/4fd667aa-9a21-4413-b3d0-6f28d13be7af)
<img width="1227" alt="Manners_Cond" src="https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/95d4b3b0-a112-4250-a0b0-9548282e7b11">
For Temp, I am proposing the bounds -5 C to 30 C. I opted to make the lower bounds the same as the sensor spec range but we could certainly consider making it 0 C if we wanted to. Our current QAQC seems to be good at removing this data already but may be a good thing to add for cleaning up former years of data (fewer/no field notes). 
![temp_real_range](https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/74167f2f-2a63-41f8-af04-2f5bf78a900b)
![temp_real_timeline](https://github.com/rossyndicate/poudre_sonde_network/assets/111379895/1139e78b-70f9-493f-abeb-093aad5cd2dd)

Thoughts? My thought for implementation is to add this anywhere where `add_spec_flag` is used. This appears to be the following sections of the `targets` workflow: `make_threshold_table` and `all_data_flagged`
